### ISSUE TITLE
Calendar mock up

### ISSUE THREAD

**Issue by pothea88** [pnc-virtual-company/2020-G1-letsgo#9]
Draw a template about calendar in explorer event view

**Comment by sokhorn990** [comment]
![calendar](https://user-images.githubusercontent.com/53551108/87016271-af943f80-c1f8-11ea-85e5-c398438cba4d.JPG)
@yonyen99  please check my task

**Comment by sokhorn990** [comment]
@sengseiha-sam  this is a calendar view please check it.
